# Generated by Django 4.2.3 on 2024-03-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buysell'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buysell',
            new_name='Buyer',
        ),
    ]
