# Generated by Django 4.2.3 on 2024-03-05 13:48

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fertilizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='category',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='price',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='category',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='price',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
