# Generated by Django 4.2.3 on 2024-05-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='fertilizer',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
