# Generated by Django 4.2.3 on 2024-05-10 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename__id_fertilizer_f_id_rename__id_product_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='_id',
            new_name='b_id',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='_id',
            new_name='s_id',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='app.customer')),
                ('fertilizers', models.ManyToManyField(to='app.fertilizer')),
                ('products', models.ManyToManyField(to='app.product')),
            ],
        ),
    ]
